language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:
  global:
install: true
before_script:
- gpg --import arpnetworking.key
script:
- mvn verify install --settings settings.xml -P ci
after_success:
- if [ \( "${TRAVIS_BRANCH}" = "master" -o -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn deploy --settings settings.xml -P ci; fi;
